export const ProjectsData = [
    {
        projectName: 'Portfolio V2',
        technologies: ['React','HTML', 'CSS', 'JavaScript'],
        imgPath: "/images/portfolio-site.png",
        website:"",
        github:"https://github.com/zseever/zs-portfolio-v2",
        description: "The current web portfolio that displays details about me, my experience, and projects I've worked on and completed, hand built with React",
    },
    {
        projectName: 'Classic Armory',
        technologies: ['React','HTML', 'CSS', 'JavaScript'],
        imgPath: "/images/classic_armory.png",
        website:"",
        github:"https://github.com/zseever/arena-ladder",
        description: "Front-end React web application that provides information for a popular online game, World of Warcraft. Using Blizzard's API to populate many areas of the site, users are able to search for characters on the game to see their details, check player versus player leaderboards, as well as swap between different game versions.",
    },
    {
        projectName: 'Investigame',
        technologies: ['React','HTML', 'CSS', 'JavaScript', 'NodeJS', 'MongoDB', 'Heroku'],
        imgPath: "/images/investigame.png",
        website:"https://investigame-p4.herokuapp.com/",
        github:"https://github.com/zseever/investigame",
        description: "Full-stack video game discovery website using the MERN stack. Allows users to find games to play based on selected criteria and store games in their personal library to keep track of. Utilized RAWG's API to fetch and populate game data while using React to display results efficiently.",
    },
    {
        projectName: 'Daily Stocks',
        technologies: ['HTML', 'CSS', 'JavaScript', 'NodeJS', 'MongoDB', 'ChartJS', 'Heroku'],
        imgPath: "/images/daily-stocks.png",
        website:"https://project-2-stocks.herokuapp.com/",
        github:"https://github.com/zseever/project-2",
        description: "Full-stack web application that displays stock data and allows users to search for and store individual stocks in watchlists and portfolios. Used Polygon's Stock API to populate stock charts and company details.",
    },
    {
        projectName: 'Impasta',
        technologies: ['Python', 'Django', 'PostgreSQL', 'Heroku'],
        imgPath: "/images/impasta.png",
        website:"https://impasta-p3.herokuapp.com/",
        github:"https://github.com/zseever/impasta",
        description: "Full-stack web application that allows users to browse restaurants, their menus, as well as submit and search for recipes that mimic the menu items' taste. Utilized Yelp's API to display real restaurants and their details, which then allowed for menu items to be added as well as user submitted recipes.",
    },
    {
        projectName: 'Solitaire',
        technologies: ['React','HTML', 'CSS', 'JavaScript'],
        imgPath: "/images/solitaire.png",
        website:"https://zseever.github.io/solitaire/",
        github:"https://github.com/zseever/solitaire",
        description: "Front-end web-based solitaire game hosted on Github Pages.",
    }
]